name: Run Gradle on PRs
on:
  push:
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            java-version: '8'
            distribution: 'temurin'
      - name: Build with gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: List Files
        run: ls
  release:
   runs-on: "ubuntu-latest"
   name: "Release"
   needs: build
   
   steps:
    - name: Upload binaries to release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
             build/libs/*
