name: Run Gradle on PRs
on:
  push:
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
    - name: Build with Gradle
      run: chmod +x ./gradlew

  release:
   runs-on: "ubuntu-latest"
   name: "Release"
   needs: build
   
   steps:
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/*
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
